### PR TITLE
De namespace

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

Remove namespace package following the formalism in https://github.com/sot/ska_sun/pull/22.

## Interface impacts

None

### Unit tests

- [x] No unit tests

### Functional tests

- Installed and confirmed expected packages / functions / versions
- Built docs and confirmed they look reasonable

### CODE REVIEW

**Review by jeanconn — APPROVED** [review]

**Comment by javierggt** [comment]
The documentation does not build for me:
```
  File "/Users/javierg/SAO/git/Ska.astro/docs/conf.py", line 23, in <module>
    from ska_astro import __version__
ImportError: cannot import name '__version__' from 'ska_astro' (unknown location)
```

and indeed I do not see `__version__` defined anywhere. Perhaps a missing `__init__.py`?

**Comment by jeanconn** [comment]
Good point.  I didn't try to build the docs but it looks like version was removed from astro.py .

**Comment by javierggt** [comment]
After seeing that, I checked the PRs that were merged that I had not looked at, and this one also was missing `__init__.py`: https://github.com/sot/ska_arc5gl/pull/14

**Comment by jeanconn** [comment]
Right.  It looks like a few of these the version was probably moved into `__init__.py` and then maybe not checked in to version control?  I fully expected to do need to go around and do some tiny fixes after we do more testing in the integ environment.

**Comment by taldcroft** [comment]
I added the missing `__init__.py`.

**Review by javierggt — APPROVED** [review]

**Pull request merged**
